spring: 
  application: 
    name: SCW-USER
  datasource: 
    username: root
    password: 123456
    url: jdbc:mysql://192.168.48.128:3306/scw?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.48.128
    port: 6379
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
 
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true
 
server:
  port: 7000
  



